version: '3'

services:
  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_PASSWORD=topsecret
    ports:
      - "27017:27017"
    volumes:
      - ./services/mongodb/cfg_data:/bitnami

  redis:
    image: redis/redis-stack
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: --save 60 1 --notify-keyspace-events KEA

  webserver-first:
    depends_on:
      - mongodb
      - redis
    build:
      context: ./services/web/
    image: webserver
    restart: on-failure
    expose:
      - "3000"
    environment:
      DB_HOST: mongodb
      REDIS_HOST: redis
      SERVER_NAME: webserver-first

  webserver-second:
    depends_on:
      - mongodb
      - redis
    build:
      context: ./services/web/
    image: webserver
    restart: on-failure
    expose:
      - "3000"
    environment:
      DB_HOST: mongodb
      REDIS_HOST: redis
      SERVER_NAME: webserver-second

  haproxy:
    depends_on:
      - webserver-first
      - webserver-second
    image: haproxy:1.7-alpine
    volumes:
      - ./services/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - webserver-first
      - webserver-second
    ports:
      - "3000:80"
