version: "3.3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      LANG: C.UTF-8
    ports:
      - 3306:3306
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data/people-one.sql:/docker-entrypoint-initdb.d/2-people-one.sql
      - ./data/people-two.sql:/docker-entrypoint-initdb.d/3-people-two.sql
  webserver:
    depends_on:
      - db
    build:
      context: .
    image: webserver
#    restart: on-failure
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: db
