version: '3'

services:
  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_PASSWORD=topsecret
    ports:
      - 27017:27017
    volumes:
      - ./services/mongodb/cfg_data:/bitnami

  redis:
    image: redis/redis-stack
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: --save 60 1 --notify-keyspace-events KEA
    volumes:
      - ./services/redis/:/data

  monolith:
    depends_on:
      - mongodb
    build:
      context: services/monolith/
    image: monolith
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      DB_HOST: mongodb
      PORT: 3000

  dialog:
    depends_on:
      - redis
    build:
      context: services/dialog/
    image: dialog
    restart: on-failure
    ports:
      - 3001:3001
    environment:
      REDIS_HOST: redis
      PORT: 3001
      MONOLITH_HOST: monolith
      MONOLITH_PORT: 3000

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8080:80
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
