version: "3.3"

services:
  master:
    image: mysql:8.0.34-debian
    restart: no
#    command: bash -c "apt-get update && apt-get install -y htop"
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      LANG: C.UTF-8
    ports:
      - 3306:3306
    volumes:
      - ./async-replication/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./async-replication/master-init.sql:/docker-entrypoint-initdb.d/1-init.sql
#      - ./async-replication/people-sample.sql:/docker-entrypoint-initdb.d/2-people-sample.sql

  slave-one:
    depends_on:
      - master
    image: mysql:8.0.34-debian
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      LANG: C.UTF-8
    ports:
      - 3307:3306
    volumes:
      - ./async-replication/slave-one.cnf:/etc/mysql/conf.d/slave-one.cnf
      - ./async-replication/slave-init.sql:/docker-entrypoint-initdb.d/1-init.sql

  slave-two:
    depends_on:
      - master
    image: mysql:8.0.34-debian
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      LANG: C.UTF-8
    ports:
      - 3308:3306
    volumes:
      - ./async-replication/slave-two.cnf:/etc/mysql/conf.d/slave-two.cnf
      - ./async-replication/slave-init.sql:/docker-entrypoint-initdb.d/1-init.sql

#  webserver:
#    depends_on:
#      - master
#    build:
#      context: .
#    image: webserver
#    ports:
#      - 3000:3000
#    environment:
#      MYSQL_HOST: master

  webserver:
    depends_on:
      - slave-one
    build:
      context: .
    image: webserver
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: slave-one
