version: "3.3"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  webserver:
    depends_on:
      - db
    build:
      context: .
    image: webserver
#    restart: on-failure
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: db
