version: "3.3"

services:
  redis:
    image: redis/redis-stack
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: --save 60 1 --notify-keyspace-events KEA

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: topsecret
      LANG: C.UTF-8
    ports:
      - 3306:3306
    volumes:
      - ./data/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./data/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data/101-people-sample.sql:/docker-entrypoint-initdb.d/2-people-sample.sql
      - ./data/tokens.sql:/docker-entrypoint-initdb.d/3-tokens.sql
      - ./data/friends.sql:/docker-entrypoint-initdb.d/4-friends.sql
      - ./data/posts.sql:/docker-entrypoint-initdb.d/5-posts-old.sql
  webserver:
    depends_on:
      - db
      - redis
    build:
      context: .
    image: webserver
    restart: on-failure
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: db
      REDIS_HOST: redis
