#login Роберт Абрамов, Воткинск
POST http://0.0.0.0:3000/login
Content-Type: application/json

{"id": "64f85634157a7964c0ad2adb", "password": "12345"}
###

# Сообщение от Роберта Абрамова Александру Абрамову
POST http://0.0.0.0:3000/dialog/64f85634157a7964c0ad2adc/send
Authorization: Bearer 41919d8e-766d-428b-bf79-fda8e17f88ff
Content-Type: application/json

{"text": "Сообщение от Роберта Абрамова Александру Абрамову - первое сообщение"}
###

#login Александр Абрамов, Домодедово
POST http://0.0.0.0:3000/login
Content-Type: application/json

{"id": "64f85634157a7964c0ad2adc", "password": "12345"}
###

# Сообщение от Александра Абрамова Роберту Абрамову
POST http://0.0.0.0:3000/dialog/64f85634157a7964c0ad2adb/send
Authorization: Bearer 62fcf349-971d-47de-9e5b-92bf5d2e835d
Content-Type: application/json

{"text": "Сообщение от Александра Абрамова Роберту Абрамову - ответ"}
###

# диалог между Робертом Абрамовым (user_id) и Александром Абрамовым (bearer)
GET http://0.0.0.0:3000/dialog/64f85634157a7964c0ad2adc/list
Authorization: Bearer 41919d8e-766d-428b-bf79-fda8e17f88ff

###

# пост первого пользователя
POST http://0.0.0.0:3000/post/create
Authorization: Bearer 674eb579-4426-4549-8972-25a8b45f1473
Content-Type: application/json

{"text": "Новый пост первого пользователя"}

###


