INSTALL PLUGIN rpl_semi_sync_replica SONAME 'semisync_replica.so';
CHANGE REPLICATION SOURCE TO SOURCE_HOST = 'master', SOURCE_PORT = 3306, SOURCE_USER = 'repl', SOURCE_PASSWORD = 'repl', SOURCE_AUTO_POSITION = 1;
START REPLICA;